version: '3'
services:
  # Create the Node backend service
  node_server:
    build:
      context: ./node_server/
      dockerfile: node.Dockerfile
    # Define a custom image name
    image: node_server
    # Define port mapping for the dev environment
    ports:
      - "8080:8080"
    # env_file: ./server/.env # TODO - uncomment this to auto-load your .env file!
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    # Bindmount volumes
    volumes:
      - ./node_server/:/usr/app
      - /usr/app/node_modules
    command: /usr/app/node_modules/.bin/nodemon src/index.js
  
  # Create the React client service
  react_client:
    build:
      context: ./react_client/
      dockerfile: react.Dockerfile
    # Define a custom image name
    image: react_client
    # Define port mapping for the dev environment
    ports:
      - "3000:3000"
    volumes:
      - ./react_client/:/usr/app
      - /usr/app/node_modules
    command: npm start
    depends_on:
      - node_server

  # Create the Database service.   
  postgres_server:
    build:
      context: ./postgres_server/
      dockerfile: postgres.Dockerfile
    # Define a custom image name
    image: postgres_server
    # Define envars for postgres db.
    environment:
      # The following password should be changed to something more secure before moving to production
      POSTGRES_PASSWORD: mydbpasswd
    # Create volume to persist data relating to the jenkins config and results. 
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  node_server:
  react_client:
  postgres-data:
  
